export const autoCompleteData = [
    'downton abby',
    '13 reasons why',
    'money heist',
    'american horror story',
    'tom clancy jack ryan',
    'house of the dragon',
    'dahmer',
    'breaking bad',
    'the serpent queen',
    'the handmaid tale',
    'a series of unfortunate events',
    'the marvelous mrs. maisel',
    'homecoming',
    'mr robot',
    'sharp objects',
    'the good doctor',
    'the good wife',
    'the good fight',
    'homeland',
    'prison break',
    'american crime story',
    'the americans',
    'big little lies',
    'the punisher',
    'hannibal',
    'bullet train',
    'elvis',
    'where the crawdads sing',
    'the batman',
    'top gun: maverick',
    'doctor strange in the multiverse of madness',
    'scream',
    'titanic',
    'star war a new hope',
    'the lord of the rings the return of the king',
    'the lion king',
    'the shawshank redemption',
    'the godfather',
    'the dark knight',
    'the godfather part 2',
    '12 angry men',
    'schindlers list',
    'pulp fiction',
    'the lord of the rings: the fellowship of the ring',
    'fight club',
    'inception',
    'the lord of the rings the two towers',
    'star wars: episode v the empire strikes back',
    'the matrix',
    'black panther',
    'once upon a time in hollywood',
    'lincoln',
    'call me by your name',
    'dunkirk',
    'parasite',
    'minion',
    'sonic the hedgehog 2',
    'scream',
    'one piece red',
    'dc league of super pets',
    'interstellar',
    'shrek',
    'game of throne',
    'the crown',
    'law and order',
    'chicago pd',
    'tell me lies',
];
